#' Filter National Forest Inventory Data 
#' 
#' @description
#' The `filter_nfi()` function provides hierarchical and non-hierarchical filtering approaches for the complex structure of National Forest Inventory data, based on user-provided condition expressions (`expr_texts`).
#' This function enables effective filtering while maintaining the relationship between plot data (parent data) and other data (child data).
#' 
#' @details
#' This function parses expressions targeting specific columns in the data frames within the provided list.
#'
#' Hierarchical filtering (`hier = TRUE`):
#' - Filters applied to plot table affect all connected child data (tree, CWD, stump, etc.).
#' - Filters applied to child data only operate within that data frame and do not affect other data frames.
#' - Example: If only coniferous forest subplots are selected in the plot table, the child data will retain only the tree, CWD, stump, etc., associated with those subplots.
#'
#' Non-hierarchical filtering (`hier = FALSE`):
#' - Filters applied to the parent data frame (plot table) do not affect the child data.
#' - Filtering results from child data affect all other parent and child data.
#' - Example: If only certain species are selected in the tree table, the plot table, CWD table, stump table, etc., will be filtered based on the remaining subplots from this selection.
#'
#' @param data : A `list` generated by \code{\link{read_nfi}}
#' @param expr_texts : A character vector; expressions specifying filtering conditions to be applied to each data frame in the list. Each expression should combine the data frame name, dollar sign, and condition (e.g., "plot$LAND_USECD == '1'"). Conditions must be valid R expressions.
#' @param hier : A logical flag (default TRUE); indicates whether to apply hierarchical filtering (`TRUE`) or non-hierarchical filtering (`FALSE`). Hierarchical filtering ensures that connected data frames are filtered based on the results of filters applied to the parent frame.
#' 
#' @return A `list` of data frames.
#' 
#' @examples
#' \dontrun{
#' # Applying hierarchical filtering to select only privately owned forest subplots
#' NFI5 <- filter_nfi(NFI5, c("plot$OWN_CD == '5'"))
#' }
#' 
#' @export
# 

filter_nfi <- function(data, expr_texts, hier=T){
  
  ## error message-------------------------------------------------------------- 
  # Extract dataframe names from each expression
  matches <- regmatches(expr_texts, gregexpr("\\w+(?=\\$)", expr_texts, perl=TRUE))
  # Check that each expression references a unique dataframe
  matches_chek <- sapply(matches, function(x) length(unique(x)) == 1)
  
  # Output an error message if any expression is invalid
  if (any(matches_chek == FALSE)) {
    stop(paste0("param 'expr_texts' requires separate expressions for each item in ", deparse(substitute(data)), ". For example: c('plot$LAND_USECD == 1', 'tree$WDY_PLNTS_TYP_CD == 1 & tree$SUBPTYP ==0')"))
  }
  
  
  ## Preprocessing--------------------------------------------------------------
  # Iterate over each expression
  for(expr_text in expr_texts){
    # Remove the dataframe name from the expression
    modified_text <- gsub("\\w+\\$", "", expr_text)
    # Convert modified text into expressions
    modified_expressions <- rlang::parse_exprs(modified_text)
    
    # Extract dataframe name
    name <- regmatches(expr_text, gregexpr("\\w+(?=\\$)", expr_text, perl=TRUE))[[1]][1]

    # Apply conditions to the 'plot' dataframe
    if(grepl("plot\\$", expr_text)){
      # Hierarchical filtering
      if(hier){
        
        filter_plot <- data$plot %>%
          filter(!!!modified_expressions)
        
        plot_all <- unique(filter_plot$SUB_PLOT)
        
        results <- lapply(data[-1], function(df) {
          df_filtered <- df[df$SUB_PLOT %in% plot_all, ]
          return(df_filtered)
        })
        
        data <- c(list(plot = filter_plot), results)
        
      }else{
        # Non-hierarchical filtering
        data$plot <- data$plot %>%
          filter(!!!modified_expressions)
      }
      
    }else{
      # Apply conditions to other dataframe
      if(hier){
        
        # Hierarchical filtering
        data[[name]] <- data[[name]] %>%
          filter(!!!modified_expressions)
        
      }else{
        
        # Non-hierarchical filtering
        filter_plot <- data[[name]] %>%
          filter(!!!modified_expressions)
      
        df <- unique(filter_plot$SUB_PLOT)
        
        results <- lapply(data, function(df) {
          df_filtered <- df[df$SUB_PLOT %in% plot_all, ]
          return(df_filtered)
        })
        
        results[[name]] <- results[[name]] %>% 
          filter(!!!modified_expressions)
        
        data <- results
        
      }
    }
  }
    
  # Return the filtered data
  return(data)
}

