#'  Calculates the importance values
#' 
#' @description
#' iv_nfi() is a function that calculates the importance values of tree species based on frequency, density and coverage.
#' Users can specify whether to include frequency in the calculation.
#' please refer to the \code{\link[BiodiversityR]{importancevalue}} function in the \pkg{BiodiversityR} package.
#' Users can also specify whether to include large tree survey plots, to focus only on tall trees and Stocked land, and to treat cluster plots as single plots.
#' 
#' @details
#' The importance value (ranging from 0 to 100) is calculated as the mean of (i) relative frequency, (ii) relative density, and (iii) relative coverage.
#' Frequency is the number of plots where a species is observed divided by the total survey plots. Relative frequency is frequency divided by the sum of all species' frequencies, multiplied by 100.
#' Density is the total number of individuals of a species. Relative density is density divided by the sum of all species' densities, multiplied by 100.
#' Coverage is the total basal area of a species. Relative coverage is coverage divided by the sum of all species' coverage, multiplied by 100.
#'
#' @param data : A `list` generated by \code{\link{read_nfi}} that contains 'plot' and 'tree' data frames.
#' @param sp : A character vector; the column name of tree species. e.g,. SP, Genus.
#' @param frequency : A logical flag; whether to use frequency in importance calculations.
#' @param grpby : 
#' @param clusterplot : A logical flag; whether to calculate for cluster plot collectively or calculate for each subplot separately.
#' @param largetreearea : A logical flag; whether to include a large tree plot as well, or only a tree plot.
#' @param stockedland : A logical flag; whether to include only stocked land or also include other types of land.
#' @param talltree : A logical flag; whether to include only tall trees or also shrubs.
#' 
#' @return  A `data.frame` that includes importance value for tree species
#' 
#' @note 
#' Species classification may be incomplete, so it might be worth considering calculating importance by genus rather than species. 
#' Since the frequencies of each species may be identical across the nation, it may be desirable to exclude frequency from the importance calculation. 
#'  
#' @examples
#' \dontrun{
#' iv_nfi(NFI5, sp="Genus")
#' }
#' 
#' @seealso
#' \code{\link[BiodiversityR]{importancevalue}} for calculating the importance values.
#' 
#' @references
#' Curtis, J. T. & McIntosh, R. P. (1951). An upland forest continuum in the prairie-forest border region of Wisconsin. Ecology, 32(3), 476–496.
#'
#' @export 


##  

iv_nfi <- function(data, sp="SP", grpby=NULL, frequency=TRUE, clusterplot=FALSE, largetreearea=FALSE, stockedland=TRUE, talltree=TRUE){
  
  ## error message-------------------------------------------------------------- 
  required_names <- c("plot", "tree")
  
  if (!all(required_names %in% names(data))) {
    missing_dfs <- required_names[!required_names %in% names(data)]
    stop("Missing required data frames in the list: ", paste(missing_dfs, collapse = ", "), call. = FALSE)
  }
  
  if(!sp %in% names(data$tree)){
    stop(paste0("param 'sp': ", sp," is not a column name in the 'tree' data frame."))
  } 
  
  ## Preprocessing--------------------------------------------------------------
  if (stockedland){ 
    data <- filter_nfi(data, c("plot$LAND_USECD == '1'"))
  }
  
  if(talltree){
    data$tree <- data$tree %>% filter(WDY_PLNTS_TYP_CD == "1")
  }
  
  if(!largetreearea){ 
    data$tree <- data$tree %>% filter(LARGEP_TREE == "0")
  }
 
  df <- left_join(data$tree[, c('CLST_PLOT', 'SUB_PLOT',"CYCLE", 'WDY_PLNTS_TYP_CD', 
                                'basal_area', 'LARGEP_TREE', sp)], 
                  data$plot[,c('CLST_PLOT', 'SUB_PLOT', "CYCLE", 'INVYR','LAND_USE', "LAND_USECD", grpby)],
                  by = c("CLST_PLOT", "SUB_PLOT", "CYCLE"))
  
  sp<- rlang::sym(sp)
  grpby<- rlang::syms(grpby)

  
  if(clusterplot){
    iv_temp <- df %>% 
      group_by(CYCLE, CLST_PLOT , !!sp, !!!grpby) %>% 
      summarise(count = n(), basal = sum(basal_area, na.rm=T),.groups = 'drop')
    plot_id <- c('CLST_PLOT')
    
    
  }else{ #subplot
    iv_temp <- df %>% 
      group_by(CYCLE, SUB_PLOT , !!sp, !!!grpby) %>% 
      summarise(count = n(), basal = sum(basal_area, na.rm=T),.groups = 'drop')
    plot_id <- c('SUB_PLOT')
  }
  
  plot_id  <- rlang::sym(plot_id)
  
  iv_temp <- data.frame(iv_temp)
  
  grpby_nm <- c("CYCLE", as.character(unlist(lapply(grpby, quo_name))))
  
  iv_temp$factor <- apply(iv_temp[grpby_nm], 1, function(row) paste(row, collapse = "_"))
  
  ## Calculating importance Value by survey cycle--------------------------------------------------------------
  iv_temp_2<-BiodiversityR::importancevalue.comp(iv_temp, site=quo_name(plot_id), species='SP', count='count', 
                                                      basal='basal', factor="factor")
  
  for(i in 2:length(iv_temp_2)){
    
    if(is.null(dim(iv_temp_2[[i]]))){
      iv_temp_2[[i]] <- as.data.frame(iv_temp_2[[i]])
      colnm_temp <- rownames(iv_temp_2[[i]])
      iv_temp_2[[i]] <- t(iv_temp_2[[i]])
      colnames(iv_temp_2[[i]]) <- colnm_temp
      rownames(iv_temp_2[[i]]) <- NULL
      iv_temp_2[[i]] <- as.data.frame(iv_temp_2[[i]])
      iv_temp_2[[i]]$species <- iv_temp$SP[iv_temp$factor ==iv_temp_2[[1]][i-1]][1]
      
    }else{
      
      iv_temp_2[[i]] <- as.data.frame(iv_temp_2[[i]])
      iv_temp_2[[i]]$species <- rownames(iv_temp_2[[i]])
      rownames(iv_temp_2[[i]]) <- NULL
      
    }
    
    iv_temp_2[[i]]$CYCLE <- sapply(strsplit(iv_temp_2[[1]][i-1], "_"), `[`, 1)
    
    if(is.null(grpby)){
      for(j in 1:length(as.character(unlist(lapply(grpby, quo_name))))){
        ivcol <- as.character(unlist(lapply(grpby, quo_name)))[j]
        iv_temp_2[[i]][ivcol] <- sapply(strsplit(iv_temp_2[[1]][i-1], "_"), `[`, j+1)
      }
    }
  }
  
  iv_temp_2[[1]] <- NULL
  
  iv <- data.table::rbindlist(iv_temp_2, fill=TRUE, use.names=TRUE)
  iv <- as.data.frame(iv)
  

  
  
  
  ## Inclusion of frequency-------------------------------------------------------------- 
  if(frequency){
    iv$importance.value <- iv$importance.value/3
  }else{
    
    iv$importance.value <- (iv$density.percent + iv$dominance.percent)/2
  }
  
  iv <- iv[, c("CYCLE", "species", setdiff(names(iv), c("CYCLE", "species")))]
  
  
  return(iv)
  
}



 
#' iv_tsvis()
#' 
#' 
#' @description
#' iv_tsvis() is a function that calculates the importance values of tree species based on frequency, density and coverage.
#' It is an internal function used within the tsvis_nfi() function.
#' iv_nfi() calculates importance by cycle, while this function calculates importance by year.
#' 
#' 
#' @param data : A `list` generated by \code{\link{read_nfi}} that contains 'plot' and 'tree' data frames.
#' @param sp : A character vector; the column name of tree species.
#' @param frequency : A logical flag; whether to use frequency in importance calculations.
#' @param grpby : 
#' @param clusterplot : A logical flag; whether to calculate for cluster plot collectively or calculate for each subplot separately.
#' @param largetreearea : A logical flag; whether to include a large tree plot as well, or only a tree plot.
#' @param stockedland : A logical flag; whether to include only stocked land or also include other types of land.
#' @param talltree : A logical flag; whether to include only tall trees or also shrubs.
#' 
#' @return  A `data.frame` that includes importance value for tree species.
#' 
#' @seealso
#' \code{\link[BiodiversityR]{importancevalue}} for calculating the importance values.
#' \code{\link[rNFI]{tsvis_nfi}}
#' 
#' @noRd 



iv_tsvis <- function(data, sp="SP", grpby=NULL , frequency=TRUE , clusterplot=FALSE, largetreearea=FALSE, stockedland=TRUE, talltree=TRUE){
  
  ## error message-------------------------------------------------------------- 
  required_names <- c("plot", "tree")
  
  if (!all(required_names %in% names(data))) {
    missing_dfs <- required_names[!required_names %in% names(data)]
    stop("Missing required data frames in the list: ", paste(missing_dfs, collapse = ", "), call. = FALSE)
  }
  
  if(!sp %in% names(data$tree)){
    stop(paste0("param 'sp': ", sp," is not a column name in the 'tree' data frame."))
  } 
  
  ## Preprocessing--------------------------------------------------------------
  if (stockedland){ 
    data <- filter_nfi(data, c("plot$LAND_USECD == '1'"))
  }
  
  if(talltree){
    data$tree <- data$tree %>% filter(WDY_PLNTS_TYP_CD == "1")
  }
  
  if(!largetreearea){ 
    data$tree <- data$tree %>% filter(LARGEP_TREE == "0")
  }
  
  
  df <- left_join(data$tree[, c('CLST_PLOT', 'SUB_PLOT',"CYCLE", 'WDY_PLNTS_TYP_CD', 
                                'basal_area', 'LARGEP_TREE', sp)], 
                  data$plot[,c('CLST_PLOT', 'SUB_PLOT', "CYCLE", 'INVYR','LAND_USE', "LAND_USECD", grpby)],
                  by = c("CLST_PLOT", "SUB_PLOT", "CYCLE"))
  
  sp<- rlang::sym(sp)
  grpby<- rlang::syms(grpby)
  
  if(clusterplot){
    iv_temp <- df %>% 
      group_by(CLST_PLOT , !!sp, !!!grpby) %>% 
      summarise(count = n(), basal = sum(basal_area, na.rm=T),.groups = 'drop')
    plot_id <- c('CLST_PLOT')
    
  }else{
    iv_temp <- df %>% 
      group_by(SUB_PLOT , !!sp, !!!grpby) %>% 
      summarise(count = n(), basal = sum(basal_area, na.rm=T),.groups = 'drop')
    plot_id <- c('SUB_PLOT')
    
  }
  
  plot_id  <- rlang::sym(plot_id)
  
  iv_temp <- data.frame(iv_temp)
  
  grpby_nm <- as.character(unlist(lapply(grpby, quo_name)))
  
  if(length(grpby) > 0){
    iv_temp$factor <- apply(iv_temp[grpby_nm], 1, function(row) paste(row, collapse = "_"))
  }else{
    iv_temp$factor <- "forest"
  }
  
  ## Calculating importance Value by survey cycle--------------------------------------------------------------
  iv_temp_2 <-BiodiversityR::importancevalue.comp(iv_temp, site=quo_name(plot_id), species='SP', count='count', 
                                                 basal='basal', factor="factor")
  
  
  for(i in 2:length(iv_temp_2)){
    
    if(is.null(dim(iv_temp_2[[i]]))){
      iv_temp_2[[i]] <- as.data.frame(iv_temp_2[[i]])
      colnm_temp <- rownames(iv_temp_2[[i]])
      iv_temp_2[[i]] <- t(iv_temp_2[[i]])
      colnames(iv_temp_2[[i]]) <- colnm_temp
      rownames(iv_temp_2[[i]]) <- NULL
      iv_temp_2[[i]] <- as.data.frame(iv_temp_2[[i]])
      iv_temp_2[[i]]$species <- iv_temp$SP[iv_temp$factor ==iv_temp_2[[1]][i-1]][1]
      
    }else{
      
      iv_temp_2[[i]] <- as.data.frame(iv_temp_2[[i]])
      iv_temp_2[[i]]$species <- rownames(iv_temp_2[[i]])
      rownames(iv_temp_2[[i]]) <- NULL
      
    }
    
    
    if(is.null(grpby)){
      for(j in 1:length(as.character(unlist(lapply(grpby, quo_name))))){
        ivcol <- as.character(unlist(lapply(grpby, quo_name)))[j]
        iv_temp_2[[i]][ivcol] <- sapply(strsplit(iv_temp_2[[1]][i-1], "_"), `[`, j)
      }
    }
  }
  
  iv_temp_2[[1]] <- NULL
  
  iv <- data.table::rbindlist(iv_temp_2, fill=TRUE, use.names=TRUE)
  
  iv  <- as.data.frame(iv) 
  rownames(iv) <- NULL
  
  
  ## Inclusion of frequency-------------------------------------------------------------- 
  if(frequency){
    iv$importance.value <- iv$importance.value/3
  }else{
    
    iv$importance.value <- (iv$density.percent + iv$dominance.percent)/2
    iv$frequency <- NULL
    iv$frequency.percent <- NULL
  }
  
  iv <- iv[, c("species", setdiff(names(iv), "species"))]
  
  return(iv)
  
}




