#' Calculates descriptive statistics
#' 
#' @description
#' summary_nfi() is a function that calculates descriptive statistics for each plot, the entire study area, or groups within the study area.
#' Users can specify whether to include large tree survey plots, to focus only on tall trees and Stocked land, and to treat cluster plots as single plots.
#' 
#' @details
#' The summary_nfi function provides statistics related to plots, including the number of cluster plots, subplots, subplots with large trees (≥30cm) observed in large tree plots, and subplots where large trees were observed.
#' It also offers statistics for trees, such as the number of individuals, large trees, dominant trees, and species.
#' Additionally, this function estimates the mean and standard error for tree measurements and stand statistics: DBH (Diameter at Breast Height), height, height of dominant trees, number of individuals per hectare, basal area per hectare, and volume per hectare.
#' 
#' @param data : A `list` generated by \code{\link{read_nfi}} that contains 'plot' and 'tree' data frames.
#' @param byplot : A logical flag; whether to calculate for each plot separately or for the entire dataset.
#' @param grpby : A character vector; variables from 'plot' tables for grouping. Use \code{c()} to combine multiple variables.
#' @param clusterplot : A logical flag; whether to calculate for cluster plot collectively or calculate for each subplot separately.
#' @param largetreearea : A logical flag; whether to include a large tree plot as well, or only a tree plot.
#' @param stockedland : A logical flag; whether to include only stocked land or also include other types of land.
#' @param talltree : A logical flag; whether to include only tall trees or also shrubs.
#' 
#' @return A `data.frame` that includes summary statistics for plot or study areas
#' 
#' @examples
#' \dontrun{
#' summary_nfi(NFI5, grpby = "AGE_CLS")
#' }
#' 
#' @export 



summary_nfi<- function(data, grpby=NULL, byplot=FALSE, clusterplot=FALSE, largetreearea=TRUE, stockedland=TRUE, talltree=TRUE){
  
  
  ## error message-------------------------------------------------------------- 
  required_names <- c("plot", "tree")
  
  if (!all(required_names %in% names(data))) {
    missing_dfs <- required_names[!required_names %in% names(data)]
    stop("Missing required data frames in the list: ", paste(missing_dfs, collapse = ", "), call. = FALSE)
  }
  
  if (!is.null(grpby)){
    
    if(!is.character(grpby)) {
      stop("param 'grpby' must be 'character'")
    }
    if(any(!grpby %in% names(data$plot))){
      stop(paste0("param 'grpby': ", grpby," is not a column name in the 'plot' data frame."))
    }
  }
  
  
  
  ## Preprocessing-------------------------------------------------------------- 
  if(clusterplot){
    plot_id <- c('CLST_PLOT')
  }else{
    plot_id <- c('SUB_PLOT')
  }
  
  
  if (stockedland){ 
    data <- filter_nfi(data, c("plot$LAND_USECD == 1"))
  }
  
  if(talltree){
    data$tree <- data$tree %>% filter(WDY_PLNTS_TYP_CD == 1)
  }
  
  if(!largetreearea){ 
    data$tree <- data$tree %>% filter(LARGEP_TREE == 0)
  }
  
  
  
  df <- left_join(data$tree[, c('CLST_PLOT', 'SUB_PLOT',"CYCLE",'INVYR', 'WDY_PLNTS_TYP_CD','CCL','CCLCD', 'SP',
                                'DBH', 'basal_area', 'HT_EST', 'VOL_EST', 'LARGEP_TREE')], 
                  data$plot[,c('CLST_PLOT', 'SUB_PLOT', "CYCLE", 'INVYR', 
                               "LAND_USE", "LAND_USECD", 'NONFR_INCL_AREA_LARGEP', 'NONFR_INCL_AREA_SUBP', grpby)], 
                  by = c("CLST_PLOT", "SUB_PLOT", "CYCLE", "INVYR"))
  
  
  plot_id  <- rlang::sym(plot_id)
  grpby  <- rlang::syms(grpby)
  
  df$tree_area <- 0.04 - ((df$NONFR_INCL_AREA_SUBP*10)/10000)
  df$largetree_area <- 0.08 - ((df$NONFR_INCL_AREA_LARGEP*10)/10000)
  df$largetree <- ifelse(df$DBH>=30, 1, 0)
  
  
  
  
  
  
  
  # statistics for plots and trees and tree measurements by site or plot
  
  if(!byplot){ # statistics for plots and trees and tree measurements per site
    
    stat_num <- df %>%
      group_by(CYCLE, !!!grpby) %>%
      summarise(num_clusterplot= n_distinct(CLST_PLOT),
                num_subplot= n_distinct(SUB_PLOT),
                num_largetree_subplot= n_distinct(SUB_PLOT[LARGEP_TREE==1]),
                num_dbh30_subplot= n_distinct(SUB_PLOT[largetree==1]),
                num_tree = n(),
                num_largetree = sum(largetree, na.rm=TRUE),
                num_dominanttree = sum(CCLCD=="a", na.rm=TRUE), 
                num_species= n_distinct(SP), .groups = 'drop')
    
    
    stat_mean <- df %>% 
      group_by(CYCLE, !!plot_id, !!!grpby) %>% 
      summarise(mean_DBH_temp = mean(DBH, na.rm=TRUE), 
                mean_H_temp = mean(HT_EST, na.rm=TRUE),
                mean_dominant_H_temp = mean(HT_EST[CCLCD=="a"], na.rm=TRUE),
                .groups = 'drop')
    
    
    stat_mean <- stat_mean %>% 
      group_by(CYCLE, !!!grpby) %>% 
      summarise(mean_DBH = mean(mean_DBH_temp, na.rm=TRUE), 
                se_DBH =  plotrix::std.error(mean_DBH_temp, na.rm=TRUE),
                mean_H = mean(mean_H_temp, na.rm=TRUE),
                se_H =  plotrix::std.error(mean_H_temp, na.rm=TRUE),
                mean_dominant_H = mean(mean_dominant_H_temp, na.rm=TRUE),
                se_dominant_H =  plotrix::std.error(mean_dominant_H_temp, na.rm=TRUE),
                .groups = 'drop')
    
    
    stat_temp <- full_join(stat_num, stat_mean, by=c('CYCLE', as.character(unlist(lapply(grpby, quo_name))))) 
    
    
  }else{ # statistics for plots and trees and tree measurements per plot
    
    
    stat_num <- df %>%
      group_by(CYCLE, !!plot_id, INVYR, !!!grpby) %>%
      summarise(num_tree = n(),
                num_largetree = sum(largetree, na.rm=TRUE),
                num_dominanttree = sum(CCLCD=="a", na.rm=TRUE), 
                num_species= n_distinct(SP), .groups = 'drop')
    
    
    stat_mean <- df %>% 
      group_by(CYCLE, !!plot_id, INVYR, !!!grpby) %>% 
      summarise(mean_DBH = mean(DBH, na.rm=TRUE), 
                mean_H = mean(HT_EST, na.rm=TRUE),
                mean_dominant_H = mean(HT_EST[CCLCD=="a"], na.rm=TRUE),
                .groups = 'drop')
    
    
    stat_temp <- full_join(stat_num, stat_mean, by=c('CYCLE', quo_name(plot_id), 'INVYR', as.character(unlist(lapply(grpby, quo_name))))) ##grpby 확인
    
  }
  
  
  ## Statistics by cluster or subplot
  
  if(clusterplot){ # Statistics by cluster
    
    
    plot_area <- df[-which(duplicated(df$SUB_PLOT)), c('CYCLE', 'INVYR', 'CLST_PLOT', 'SUB_PLOT', 'largetree_area', 'tree_area')]
    
    plot_area <- plot_area %>%
      group_by(CYCLE, !!plot_id,  INVYR) %>%
      summarise(largetree_area = sum(largetree_area, na.rm=TRUE),
                tree_area= sum(tree_area, na.rm=TRUE),.groups = 'drop')
    
    
    stat_ha <- df %>% 
      group_by(CYCLE, !!plot_id, INVYR, largetree, !!!grpby) %>% 
      summarise(tree_temp = n(), 
                basal_temp= sum(basal_area, na.rm=TRUE),
                volume_temp= sum(VOL_EST, na.rm=TRUE),
                .groups = 'drop')
    
    
    stat_ha <- full_join(stat_ha, plot_area, by=c('CYCLE', 'INVYR', quo_name(plot_id))) #, as.character(unlist(lapply(grpby, quo_name)))
    
    condition <- (names(stat_ha) %in% c("tree_temp","basal_temp","volume_temp"))
    
    
    
    if(!largetreearea){ ## Statistics by cluster (Excluding largetree plots)
      
      
      condition_ha <- c("tree_n_ha","basal_m2_ha","volume_m3_ha")
      stat_ha[condition_ha] <-  NA
      stat_ha <- as.data.frame(stat_ha)
      
      condition_ha <- (names(stat_ha) %in% c("tree_n_ha","basal_m2_ha","volume_m3_ha"))
      
      stat_ha[condition_ha] <- 
        lapply(stat_ha[condition], function(x) (x/stat_ha$tree_area))
      
      
      stat_ha[condition] <- NULL
      stat_ha$tree_area <- NULL
      stat_ha$largetreearea <- NULL
      
      
      
      
      
    }else{ ## Statistics by cluster (Including largetree plots)
      
      stat_ha[condition] <- lapply(stat_ha[condition], function(x) ifelse(stat_ha$largetree == 1, 
                                                                          x/(stat_ha$largetree_area),
                                                                          x/(stat_ha$tree_area)))
      
      stat_ha <- stat_ha %>% 
        group_by(CYCLE, INVYR, !!plot_id, !!!grpby) %>% 
        summarise(tree_n_ha = sum(tree_temp, na.rm=TRUE),
                  basal_m2_ha = sum(basal_temp, na.rm=TRUE),
                  volume_m3_ha = sum(volume_temp, na.rm=TRUE),.groups = 'drop')
    }
    
    
  }else{ ## Statistics by subplot
    
    stat_ha <- df %>% 
      group_by(CYCLE, !!plot_id, INVYR, largetree, largetree_area, tree_area, !!!grpby) %>% 
      summarise(tree_temp = n(), 
                basal_temp= sum(basal_area, na.rm=TRUE),
                volume_temp= sum(VOL_EST, na.rm=TRUE),
                .groups = 'drop')
    
    condition <- (names(stat_ha) %in% c("tree_temp","basal_temp","volume_temp"))
    
    
    if(!largetreearea){## Statistics by subplot (Excluding largetree plots)
      
      condition_ha <- c("tree_n_ha","basal_m2_ha","volume_m3_ha")
      stat_ha[condition_ha] <-  NA
      stat_ha <- as.data.frame(stat_ha)
      
      condition_ha <- (names(stat_ha) %in% c("tree_n_ha","basal_m2_ha","volume_m3_ha"))
      
      stat_ha[condition_ha] <- 
        lapply(stat_ha[condition], function(x) (x/stat_ha$tree_area))
      
      
      stat_ha[condition] <- NULL
      stat_ha$tree_area <- NULL
      stat_ha$largetreearea <- NULL
      
      
      
    }else{ ## Statistics by subplot (Including largetree plots)
      
      stat_ha[condition] <- lapply(stat_ha[condition], function(x) ifelse(stat_ha$largetree == 1, 
                                                                          x/(stat_ha$largetree_area),
                                                                          x/(stat_ha$tree_area)))
      
      stat_ha <- stat_ha %>% 
        group_by(CYCLE, INVYR, !!plot_id, !!!grpby) %>% 
        summarise(tree_n_ha = sum(tree_temp, na.rm=TRUE),
                  basal_m2_ha = sum(basal_temp, na.rm=TRUE),
                  volume_m3_ha = sum(volume_temp, na.rm=TRUE),.groups = 'drop')
    }
    
  }
  
  
  
  
  
  ##  join (statistics for plots and trees by site and Statistics by cluster or subplot) 
  if(!byplot){
    
    stat_ha <- stat_ha %>% 
      group_by(CYCLE, !!!grpby) %>% 
      summarise(mean_tree_n_ha = mean(tree_n_ha, na.rm=TRUE),
                se_tree_n_ha =  plotrix::std.error(tree_n_ha, na.rm=TRUE),
                mean_basal_m2_ha = mean(basal_m2_ha, na.rm=TRUE),
                se_basal_m2_ha =  plotrix::std.error(basal_m2_ha, na.rm=TRUE),
                mean_volume_m3_ha = mean(volume_m3_ha, na.rm=TRUE),
                se_volume_m3_ha =  plotrix::std.error(volume_m3_ha, na.rm=TRUE),.groups = 'drop')
    
    stat_data <- full_join(stat_temp, stat_ha, by=c('CYCLE', as.character(unlist(lapply(grpby, quo_name)))))
    
    
  }else{
    
    stat_data <- full_join(stat_temp, stat_ha, by=c('CYCLE', quo_name(plot_id), 'INVYR', as.character(unlist(lapply(grpby, quo_name))))) 
  }
  
  
  
  
  
  
  
  return(stat_data)
  
} 