#' Visualizes time series data
#' 
#' @description
#' tsvis_nfi() is a function that analyzes and visualizes data in a time series format. It can visualize 'biomass', 'cwd', and 'iv' data as 'table', 'line', 'bar', or 'map'.
#' Users need to select the specific biomass variable, such as volume or carbon, to visualize biomass. 
#' If you want to view biomass on a map, you must choose the administrative unit level for the map visualization.
#' 
#' @param data : A `list` generated by \code{\link{read_nfi}} that contains 'plot' and 'tree' data frames.
#' @param y : A character vector; the variable to visualize. Must be one of 'biomass', 'cwd', 'iv'.
#' @param bm_type : A character vector; the specific variable to visualize for 'biomass' or 'cwd'. Must be one of 'volume', 'biomass', 'AG_biomass', 'carbon', 'co2'.
#' @param output : A character vector; the desired type of visualization. Must be one of 'table', 'line', 'bar', 'map'.
#' @param admin : A character vector; the administrative unit for visualizing 'biomass' or 'cwd' as a map. Must be one of 'sido', 'sgg', 'emg'.
#' @param strat : A character vector; the variable used for post-stratification. In the National Forest Inventory of Korea, it is typically used by forest type.
#' @param clusterplot : A logical flag; whether to calculate for cluster plot collectively or calculate for each subplot separately.
#' @param largetreearea : A logical flag; whether to include a large tree plot as well, or only a tree plot.
#' @param stockedland : A logical flag; whether to include only stocked land or also include other types of land.
#' @param talltree : A logical flag; whether to include only tall trees or also shrubs.
#' @param sp : A character vector; the column name of tree species.
#' @param frequency : A logical flag; whether to use frequency in importance calculations.
#' 
#' @return An object of class \pkg{ggplot}.
#' 
#' @examples
#' \dontrun{
#' tsvis_nfi(NFI5, y="iv", output="bar")
#' tsvis_nfi(NFI5, admin="sido", y="biomass", bm_type="carbon", output="map")
#' }
#' 
#' @note 
#' To visualize data as a map, you need to agree to install the `kadmin` package during the function execution or install it in advance. 
#' The `kadmin` package loads shapefiles for Korea's Si, Do or Si, Gun, Gu or Eup, Myeon, Dong.
#' `drat::addRepo("SYOUNG9836") install.packages("kadmin")` or `remotes::install_github("SYOUNG9836/kadmin")`
#' 
#' @seealso
#' \code{\link[rNFI]{iv_nfi}} for calculating the importance values.
#' \code{\link[rNFI]{biomass_nfi}} for calculating the biomass.
#' \code{\link[rNFI]{cwd_biomass_nfi}} for calculating the biomass of Coarse Woody Debris.
#' 
#' @export

tsvis_nfi <- function(data, admin=NULL, y = "biomass", bm_type = NULL, output ="line", strat="FORTYP_SUB", 
                         clusterplot=FALSE, largetreearea=TRUE, stockedland=TRUE, talltree=TRUE, sp="SP", frequency= TRUE){
  
  
  ## error message-------------------------------------------------------------- 
  if(y != "iv" & output != "table"){
    if(is.null(y)){
      stop("param 'y' is a required parameter")
    }else{
      if(!is.character(bm_type)) {
        stop("param 'bm_type' must be 'character'")
      }
      if(!bm_type %in%  c("volume", "biomass", "AG_biomass", "carbon", "co2")){
        stop("param 'bm_type' must be one of 'volume', 'biomass', 'AG_biomass', 'carbon', 'co2'")
      }
    }
  }
  
  
  if(y != "iv" & output == "map"){
    if(!stringr::str_detect(admin,'_CD$')){
      stop("param 'admin' must be in administrative district code")
    }
    if(!admin %in%  c('sido', 'sgg', 'emg')){
      stop("param 'admin' must be one of 'sido', 'sgg', 'emg'")
    }
    
    admin <- switch(admin,
                    "sido" = "SIDO_CD",
                    "sgg" = "SGG_CD",
                    "EMD_CD")
    
  }
  
  if(y == "iv" & output == "map"){
    stop("Importance value cannot be visualized by map")
  }
  
  
  if(!y %in%  c("biomass", "cwd", "iv")){
    stop("param 'y' must be one of 'biomass', 'cwd', 'iv'")
  }
  
  
  if(!output %in%  c("table", "line", 'bar',"map")){
    stop("param 'output' must be one of 'table', 'line', 'bar', 'map'")
  }
  
  
  if(output %in%  c("line", 'bar',"map")){
    ggplot2::theme_set(ggplot2::theme_classic())
    ggplot2::theme_update(text = ggplot2::element_text(size=13))
  }
  
  if(y %in%  c("biomass", "cwd")){
    if (clusterplot){
      if(strat=="FORTYP_SUB"){
        warning("When the param 'clusterplot' is set to TRUE, param 'strat' uses FORTYP_CLST (the forest type for the cluster plot) instead of FORTYP_SUB (the forest type for each subplot).")
        
        strat <- c("FORTYP_CLST")
      }
    }
  }
  
  
  # if(output == "map"){
  #    if (!requireNamespace("kadmin", quietly = TRUE)) {
  #      consent <- utils::menu(choices = c("Yes", "No"), title = "The functionality you are trying to use requires 'kadmin'. Do you want to install it? (Yes/No)")
  #      
  #       #Install the package if agreed upon.
  #      if (consent == 1) {
  #        drat::addRepo("SYOUNG9836")
  #        install.packages("kadmin")
  #      } else {
  #        stop("Package 'kadmin' is not installed. This functionality cannot be used without installing the required package.")
  #      }
  #    }
  #  }
  
  
  ## Preprocessing--------------------------------------------------------------
  tsvis_list <- vector("list", length = (length(unique(data$plot$INVYR)-4)))
  
  for(i in 1:(length(unique(data$plot$INVYR))-4)){ 
    
    s_year <- min(data$plot$INVYR)+i-1
    e_year <- min(data$plot$INVYR)+i-1+4
    
    data_temp <- lapply(data, function(x) x %>% filter(x$INVYR  >= s_year & x$INVYR <= e_year))
    
    
    if(y == "biomass"){
      tsvis_list[[i]] <- biomass_tsvis(data_temp, grpby = admin, strat = strat, clusterplot = clusterplot,
                                         largetreearea = largetreearea, stockedland = stockedland, talltree = talltree)
      tsvis_list[[i]]$year <- e_year
    }else if(y == "cwd"){
      tsvis_list[[i]] <- cwd_biomass_tsvis(data_temp, grpby = admin, strat = strat, stockedland = stockedland)
      tsvis_list[[i]]$year <- e_year
    }else if(y == "iv"){
      tsvis_list[[i]] <- iv_tsvis(data_temp, sp = sp, frequency = frequency, clusterplot = clusterplot,
                                  largetreearea = largetreearea, stockedland = stockedland, talltree = talltree)
      tsvis_list[[i]]$year <- e_year
    }else{
      stop(paste( y, ' does not exist.'))
    }
  }
  
  
  tsvis_df <- data.table::rbindlist(tsvis_list, fill=TRUE, use.names=TRUE)
  tsvis_df <- as.data.frame(tsvis_df)
  tsvis_df$year <- as.character(tsvis_df$year)
  
  
  # Calculate biomass or CWD--------------------------------------------------------------
  if(y =="biomass" | y =="cwd"){ 
    
    # table--------------------------------------------------------------
    if(output =="table"){
      
      tsvis <- ggpubr::ggtexttable(tsvis_df,rows=NULL,
                           theme=ttheme(
                             colnames.style = colnames_style(color = "#333333", size=13 ,fill = "#EAEDF0"), 
                             tbody.style= tbody_style( face="plain", color = "#333333", fill=c("white","#F4F6F7")),
                             padding = unit(c(7,7),"mm")))
      
      
    }else if(output =="map"){ # map
      
      
      district_code[,1] <- (gsub("-", "", district_code[,1]))
      tsvis_df$name <- unlist(lapply(tsvis_df[, admin], 
                                    FUN=function(x){district_code$district_name[which(x==district_code$district_CD)]}))
      
      if(nchar(tsvis_df[, admin][1]) == 10){
        emd <- kadmin::emd
        bm_map <- right_join(emd, tsvis_df, by=c("EMD_CD" = quo_name(admin)))
        #bm_map <- sf::st_as_sf( bm_map )
        
      }else if(nchar(tsvis_df[,admin][1]) == 5){
        sgg <- kadmin::sgg
        bm_map <- right_join(sgg, tsvis_df, by=c("SIG_CD" = quo_name(admin)))
        #bm_map <- sf::st_as_sf( bm_map )
        
      }else{
        do <- kadmin::do
        bm_map <- right_join(do, tsvis_df, by=c("CTPRVN_CD" = quo_name(admin)))
        #bm_map <- sf::st_as_sf( bm_map )
      }
      
      value <- colnames(bm_map)[grep(paste0("^", bm_type, "|^cwd_", bm_type), colnames(bm_map))]
      se <- colnames(bm_map)[grep(paste0("^rse_", bm_type, "|^rse_cwd_", bm_type), colnames(bm_map))]
      
      value  <- rlang::sym(value)
      se  <- rlang::sym(se)
      
      ylab <- case_when(
        bm_type == "volume" ~ expression(paste("Volume (", m^{3}, ")")),
        bm_type == "biomass" ~ expression(paste("Biomass (ton/ha)")),
        bm_type == "AG_biomass" ~ expression(paste("AG biomass (ton/ha)")),
        bm_type == "carbon" ~ expression(paste("Carbon stock (tC/ha)")),
        bm_type == "co2" ~ expression(paste(CO[2]," stock (t", CO[2], "/ha)")),
        TRUE ~ expression(0)
        
      )
      
     tsvis_value <- ggplot2::ggplot(bm_map) + 
       ggplot2::geom_sf(ggplot2::aes(fill = !!value , geometry = geometry))+
       ggplot2::coord_sf(expand = FALSE, lims_method = "geometry_bbox")+
        #scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+
       ggplot2::facet_wrap(~year)+
       ggplot2::theme(axis.text.x = ggplot2::element_text(angle =90, vjust = 1))+
        #ggspatial::annotation_scale(location = "bl", width_hint = 0.1) +
        #ggspatial::annotation_north_arrow(location = "bl", which_north = "true", 
        #                       pad_x = unit(0.0, "in"), pad_y = unit(0.1, "in"),
        #                       style = north_arrow_fancy_orienteering)+
       ggplot2::scale_fill_viridis_c(direction = -1,  alpha = .7)+
       ggplot2::labs(fill=ylab)
      
      
      tsvis_se <- ggplot2::ggplot(bm_map)+ 
        ggplot2::geom_sf(ggplot2::aes(fill = !!se , geometry = geometry))+
        ggplot2::coord_sf(expand = FALSE, lims_method = "geometry_bbox")+
        ggplot2::facet_wrap(~year)+
        ggplot2::theme(axis.text.x = ggplot2::element_text(angle =90, vjust = 1))+
        #ggspatial::annotation_scale(location = "bl", width_hint = 0.1) +
        #ggspatial::annotation_north_arrow(location = "bl", which_north = "true", 
        #                       pad_x = unit(0.0, "in"), pad_y = unit(0.1, "in"),
        #                       style = north_arrow_fancy_orienteering)+
        ggplot2::scale_fill_viridis_c(direction = -1,  alpha = .7, option="magma")+
        ggplot2::labs(fill=paste0("RSE (%)", paste(rep(" ", nchar(value)-1), collapse = "")))
      
      tsvis <- cowplot::plot_grid(tsvis_value, tsvis_se, ncol = 2)
      
      
      
    }else if(output =="line"){ 
      #line graph--------------------------------------------------------------
      tsvis_df$name <- tsvis_df[,admin]
      
      value <- colnames(tsvis_df)[grep(paste0("^", bm_type, "|^cwd_", bm_type), colnames(tsvis_df))]
      se <- colnames(tsvis_df)[grep(paste0("^rse_", bm_type, "|^rse_cwd_", bm_type), colnames(tsvis_df))]
      
      value  <- rlang::sym(value)
      se  <- rlang::sym(se)
      
      tsvis <- ggplot2::ggplot(tsvis_df, ggplot2::aes(x=year)) + 
        ggplot2::geom_line(ggplot2::aes(y=!!value, group = name, color = reorder(name, -!!value)), linewidth = 1.1)+ 
        ggplot2::geom_point(ggplot2::aes(y=!!value, group = name, color = reorder(name, -!!value)), size = 3)+ 
        ggplot2::geom_errorbar(ggplot2::aes(ymin=!!value-!!se, ymax=!!value+!!se, color = reorder(name, -!!value)),
                      width=0.2, size=0.8)+ 
        ggplot2::theme(axis.title.x = ggplot2::element_text(vjust=-1.5),
              axis.title.y = ggplot2::element_text(vjust=4),
              plot.margin = ggplot2::unit(c(0.3,0.1,0.5,0.6), "cm"), 
              legend.title = ggplot2::element_blank())+
        ggplot2::scale_color_viridis_d()+ 
        ggplot2::labs(x="Year", y=ylab)
      
    }else if(output =="bar"){
      #bar graph--------------------------------------------------------------
      tsvis_df$name <- tsvis_df[,admin]
      
      value <- colnames(tsvis_df)[grep(paste0("^", bm_type, "|^cwd_", bm_type), colnames(tsvis_df))]
      se <- colnames(tsvis_df)[grep(paste0("^rse_", bm_type, "|^rse_cwd_", bm_type), colnames(tsvis_df))]
      
      value  <- rlang::sym(value)
      se  <- rlang::sym(se)
      
      tsvis <- ggplot2::ggplot(tsvis_df, ggplot2::aes(x=year, group = name))+
        ggplot2::geom_bar(ggplot2::aes(y=!!value, fill = reorder(name, -!!value)), size = 1, stat='identity', position = 'dodge')+ 
        ggplot2::geom_errorbar(ggplot2::aes(ymin=!!value-!!se, ymax=!!value+!!se),
                      position=ggplot2::position_dodge(0.9),width=0.2, size=0.8)+
        ggplot2::theme(axis.title.x = ggplot2::element_text(vjust=-1.5),
              axis.title.y = ggplot2::element_text(vjust=4),
              plot.margin = ggplot2::unit(c(0.3,0.1,0.5,0.6), "cm"), 
              legend.title = ggplot2::element_blank())+
        ggplot2::scale_fill_viridis_d()+ 
        ggplot2::labs(x="Year", y=ylab)
        
      
    
    }else{
      
      stop(paste( output, ' does not exist.'))
      
    }
    
    # Calculate Importance value
  }else if(y=="iv"){ 
    # table--------------------------------------------------------------
    if(output =="table"){
      
      tsvis <- ggpubr::ggtexttable(tsvis_df,rows=NULL,
                           theme=ttheme(
                             colnames.style = colnames_style(color = "#333333", size=13 ,fill = "#EAEDF0"), 
                             tbody.style= tbody_style( face="plain", color = "#333333", fill=c("white","#F4F6F7")),
                             padding = unit(c(7,7),"mm")))
                           
      
    } else if(output =="line"){
      # line graph--------------------------------------------------------------
      tsvis <- tsvis_df %>% 
        filter(species %in% reorder(species, importance.value)[1:20]) %>%
        ggplot2::ggplot() + 
        ggplot2::geom_line(ggplot2::aes(x=year, y=importance.value, group = species, color = reorder(species, -importance.value)), linewidth = 1.1)+ 
        ggplot2::theme(axis.title.x = ggplot2::element_text(vjust=-1.5),
              axis.title.y = ggplot2::element_text(vjust=4),
              plot.margin = ggplot2::unit(c(0.3,0.1,0.5,0.6), "cm"), 
              legend.title = ggplot2::element_blank()) + 
        ggplot2::labs(x= "Year", y="Importance value (%)")
      
      
    } else if(output =="bar"){
      # bar graph--------------------------------------------------------------
      tsvis <- tsvis_df %>% 
        filter(species %in% reorder(species, importance.value)[1:20]) %>%
        ggplot2::ggplot(ggplot2::aes(y = importance.value, x = reorder(species, importance.value))) +
        ggplot2::geom_bar(ggplot2::aes(fill = reorder(species, importance.value)), width=0.6, stat="identity") +
        #geom_text(aes(label= paste0(round(importance.value, 1),"%")), size=3.5)+
        #scale_y_continuous(limits = c(min(Gangwon_iv$importance.value) - 1, max(Gangwon_iv$importance.value) + 6)) +
        ggplot2::coord_flip() +
        ggplot2::facet_wrap(~year)+
        ggplot2::theme(axis.title.x = ggplot2::element_text(vjust=-1.5),
              axis.title.y = ggplot2::element_blank(),
              plot.margin = ggplot2::unit(c(0.3,0.2,0.5,0.1), "cm"),
              legend.position = "none")+ 
        ggplot2::labs(y="Importance value (%)")
      
      
    } else{
      
      stop(paste( output, ' does not exist.'))
      
    }
    
    
    
    
  }
  
  return(tsvis)
  
}







